#Eigenentwicklung, die Dockercompose Datei damit die Container bereitgestellt werden.
services:
  mysql:
    image: mariadb
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=xenivcdi
      - MYSQL_PASSWORD=mysqlserver
      - MYSQL_USER=xenivcdi
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./db:/var/lib/mysql
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  flask:
    build: .
    container_name: flask
    restart: always
    environment:
        - DATABASE_URL=mysql+pymysql://xenivcdi:mysqlserver@dbserver/xenivcdi
    volumes:
      - ./app:/app:ro
    depends_on:
      - mysql
    links:
      - mysql:dbserver
